config/routes.rb
StenverHome::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  get "comments/edit"
  get "comments/update"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :articles
  root  'articles#index'

  match '/coolStuff', to: 'public#coolStuff',    via: 'get'
  match '/experience', to: 'public#experience',   via: 'get'
  match '/about', to: 'public#about', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/sessions', to: 'sessions#create', via: 'post'
  match '/signout', to: 'sessions#destroy', via: 'delete'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  has_many :comments
  validates :user_id, presence: true
  validates :title, presence: true
  validates :text, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
  validates :text, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  before_create :create_remember_token
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private

    def signed_in_user
      store_location
      redirect_to signin_url, notice: "Please identify yourself" unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user) or current_user.admin?
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.create(article_params)
    if @article.save
      flash[:success] = "Article successfully created."
      redirect_to @article
    else
      render :new
    end
  end

  def destroy
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end

  def create
  end

  def edit
  end

  def update
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController

  def coolStuff
  end

  def about
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if signed_in?
      redirect_to root_url
    end
  end

  def create
  	user = User.find_by(email: session_params[:email].downcase)
  	if user && user.authenticate(session_params[:password])
  		sign_in user
      redirect_back_or user
  	else
  		flash.now[:error] = "Im sorry to say this to you, hero, but either you forgot your name or you dont know your secret word"
  		render :new
  	end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

  private
  	def session_params
  		params[:session]
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update, :index, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
    if signed_in?
      redirect_to root_url
    end
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Dungeon! Choose your campaign and prepare to suffer."
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Subject successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
  	remember_token = User.new_remember_token
  	cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user	
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
  	!current_user.nil?
  end

  def current_user=(user)
	@current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<li>
  <h3><%= link_to article.title, article %></h3>
  <%= article.text[0..500] %>... <%= link_to "(read more)", article %>
</li>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<% provide(:title, 'New Article') %>
<% content_for :head do %>
  <%= stylesheet_link_tag    "wmd.css" %>
  <%= javascript_include_tag "showdown.js" %>
<% end %>

<h1>New Article</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @article, :html => { :class => 'Article', :text => 'wmd-input' } do |f| %>

      <%= render "shared/error_messages", object: @article %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <div id="wmd-button-bar" class="wmd-panel"></div>
      <br/>
      <textarea id="wmd-input" name="article[text]" class="wmd-panel"></textarea>
      <br/>
      <div id="wmd-preview" class="wmd-panel"></div>
      <br/>
      <div id="wmd-output" class="wmd-panel"></div>

      <%= f.submit "Create article", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "wmd.js" %>

app/views/articles/index.html.erb
<% provide(:title, 'News') %>
<div class="container">
<%= will_paginate %>

<ul class="list-row">
  <%= render @articles %>
</ul>
<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<% content_for :head do %>
  <%= stylesheet_link_tag    "wmd.css" %>
  <%= javascript_include_tag "showdown.js" %>
<% end %>

<h1>New Article</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@article) do |f| %>
      <%= render "shared/error_messages", object: @article %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :text %>
      <div id="wmd-button-bar" class="wmd-panel"></div>
      <br/>
      <textarea id="wmd-input" name="article[text]" class="wmd-panel"></textarea>
      <br/>
      <div id="wmd-preview" class="wmd-panel"></div>
      <br/>
      <div id="wmd-output" class="wmd-panel"></div>

      <%= f.submit "Create article", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<%= javascript_include_tag "wmd.js" %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<div class="container">
<h2><%= @article.title %> </h2>
<p><%= simple_format @article.text %> </p>
<span class="timestamp">
Last updated <%= time_ago_in_words(@article.updated_at) %> ago</p>
</span>
<% if current_user.admin? %>
  <span><%= link_to "Edit article", edit_article_path(@article) %></span> </br>
<% end %>
<ul class="list-row">
  <%= render @comments %>
</ul>
</div>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>

app/views/comments/_comment.html.erb
<li>
  <%= link_to comment.user.name, comment.user %>: <%= comment.text %>
  <span class="timestamp">
    posted <%= time_ago_in_words(comment.updated_at) %></p>
  </span>
</li>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Stenver Jerkku", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <!-- <li><%= link_to "News", root_path %></li> -->
        <li><%= link_to "Cool Stuff", coolStuff_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if signed_in? %>
          <li><%= link_to "Dungeon", user_path(current_user) %></li>
          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        <% else %>
          <li><%= link_to "Dungeon", signin_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Stenver Jerkku | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>

</head>
<body>

<%= render '/layouts/header'%>

<div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
</div>

<%= render '/layouts/footer'%>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	| <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" }%>
  <% end %>
</li>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destory.html.erb
<h1>Users#destory</h1>
<p>Find me in app/views/users/destory.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit " + @user.name) %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: @user %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render '/shared/error_messages', object: @user%>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
       <div class="user_options">
        <span><%= link_to "Edit", edit_user_path(@user) %></span> </br>
        <% if current_user.admin? %>
          <span><%= link_to "See all users", users_path %></span> </br>
          <span><%= link_to "Create an article", new_article_path %></span> </br>
        <% end %>
       </div>
    </section>
  </aside>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>